# Generated by Django 4.2 on 2023-05-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="failed_login_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_failed_attempt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
